// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ho-oh/pkg/bulbasur_v1/bulbasur.proto

package ho_oh

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthTokenDto struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiryDuration       uint64   `protobuf:"varint,2,opt,name=expiry_duration,json=expiryDuration,proto3" json:"expiry_duration,omitempty"`
	ExpiryTimeUnit       TimeUnit `protobuf:"varint,3,opt,name=expiry_time_unit,json=expiryTimeUnit,proto3,enum=core.TimeUnit" json:"expiry_time_unit,omitempty"`
	Status               Status   `protobuf:"varint,4,opt,name=status,proto3,enum=core.Status" json:"status,omitempty"`
	EntityId             string   `protobuf:"bytes,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthTokenDto) Reset()         { *m = AuthTokenDto{} }
func (m *AuthTokenDto) String() string { return proto.CompactTextString(m) }
func (*AuthTokenDto) ProtoMessage()    {}
func (*AuthTokenDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_23eb8333366d2ed7, []int{0}
}

func (m *AuthTokenDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthTokenDto.Unmarshal(m, b)
}
func (m *AuthTokenDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthTokenDto.Marshal(b, m, deterministic)
}
func (m *AuthTokenDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthTokenDto.Merge(m, src)
}
func (m *AuthTokenDto) XXX_Size() int {
	return xxx_messageInfo_AuthTokenDto.Size(m)
}
func (m *AuthTokenDto) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthTokenDto.DiscardUnknown(m)
}

var xxx_messageInfo_AuthTokenDto proto.InternalMessageInfo

func (m *AuthTokenDto) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthTokenDto) GetExpiryDuration() uint64 {
	if m != nil {
		return m.ExpiryDuration
	}
	return 0
}

func (m *AuthTokenDto) GetExpiryTimeUnit() TimeUnit {
	if m != nil {
		return m.ExpiryTimeUnit
	}
	return TimeUnit_unknown_time_unit
}

func (m *AuthTokenDto) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_unknown_status
}

func (m *AuthTokenDto) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

type AuthTokenAttributeDto struct {
	AuthTokenId          string   `protobuf:"bytes,1,opt,name=auth_token_id,json=authTokenId,proto3" json:"auth_token_id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthTokenAttributeDto) Reset()         { *m = AuthTokenAttributeDto{} }
func (m *AuthTokenAttributeDto) String() string { return proto.CompactTextString(m) }
func (*AuthTokenAttributeDto) ProtoMessage()    {}
func (*AuthTokenAttributeDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_23eb8333366d2ed7, []int{1}
}

func (m *AuthTokenAttributeDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthTokenAttributeDto.Unmarshal(m, b)
}
func (m *AuthTokenAttributeDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthTokenAttributeDto.Marshal(b, m, deterministic)
}
func (m *AuthTokenAttributeDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthTokenAttributeDto.Merge(m, src)
}
func (m *AuthTokenAttributeDto) XXX_Size() int {
	return xxx_messageInfo_AuthTokenAttributeDto.Size(m)
}
func (m *AuthTokenAttributeDto) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthTokenAttributeDto.DiscardUnknown(m)
}

var xxx_messageInfo_AuthTokenAttributeDto proto.InternalMessageInfo

func (m *AuthTokenAttributeDto) GetAuthTokenId() string {
	if m != nil {
		return m.AuthTokenId
	}
	return ""
}

func (m *AuthTokenAttributeDto) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AuthTokenAttributeDto) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type LoginResponse struct {
	Response             *AuthTokenDto `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23eb8333366d2ed7, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetResponse() *AuthTokenDto {
	if m != nil {
		return m.Response
	}
	return nil
}

type LoginRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23eb8333366d2ed7, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LogoutRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenId              string   `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23eb8333366d2ed7, []int{4}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LogoutRequest) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23eb8333366d2ed7, []int{5}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type RefreshTokenRequest struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRequest) Reset()         { *m = RefreshTokenRequest{} }
func (m *RefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRequest) ProtoMessage()    {}
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23eb8333366d2ed7, []int{6}
}

func (m *RefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRequest.Unmarshal(m, b)
}
func (m *RefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRequest.Merge(m, src)
}
func (m *RefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRequest.Size(m)
}
func (m *RefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRequest proto.InternalMessageInfo

func (m *RefreshTokenRequest) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *RefreshTokenRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RefreshTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshTokenResponse struct {
	Response             *AuthTokenDto `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RefreshTokenResponse) Reset()         { *m = RefreshTokenResponse{} }
func (m *RefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenResponse) ProtoMessage()    {}
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23eb8333366d2ed7, []int{7}
}

func (m *RefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenResponse.Unmarshal(m, b)
}
func (m *RefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenResponse.Merge(m, src)
}
func (m *RefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenResponse.Size(m)
}
func (m *RefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenResponse proto.InternalMessageInfo

func (m *RefreshTokenResponse) GetResponse() *AuthTokenDto {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthTokenDto)(nil), "bulbasur_v1.AuthTokenDto")
	proto.RegisterType((*AuthTokenAttributeDto)(nil), "bulbasur_v1.AuthTokenAttributeDto")
	proto.RegisterType((*LoginResponse)(nil), "bulbasur_v1.LoginResponse")
	proto.RegisterType((*LoginRequest)(nil), "bulbasur_v1.LoginRequest")
	proto.RegisterType((*LogoutRequest)(nil), "bulbasur_v1.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "bulbasur_v1.LogoutResponse")
	proto.RegisterType((*RefreshTokenRequest)(nil), "bulbasur_v1.RefreshTokenRequest")
	proto.RegisterType((*RefreshTokenResponse)(nil), "bulbasur_v1.RefreshTokenResponse")
}

func init() {
	proto.RegisterFile("ho-oh/pkg/bulbasur_v1/bulbasur.proto", fileDescriptor_23eb8333366d2ed7)
}

var fileDescriptor_23eb8333366d2ed7 = []byte{
	// 583 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0xd3, 0x36, 0x4d, 0x6e, 0xd2, 0x50, 0x0d, 0x29, 0xa4, 0x0e, 0x42, 0xa9, 0x55, 0x89,
	0xa8, 0x12, 0x31, 0x0d, 0x42, 0x42, 0x65, 0x55, 0xa8, 0x90, 0x22, 0xc1, 0xc6, 0x0d, 0x0b, 0xd8,
	0x58, 0x8e, 0x3d, 0x89, 0x47, 0x49, 0x3c, 0x66, 0x1e, 0x81, 0x08, 0xb1, 0xe1, 0x17, 0xf8, 0x21,
	0xd6, 0x6c, 0xf9, 0x05, 0x3e, 0x04, 0x79, 0x66, 0xec, 0x3a, 0x10, 0xc1, 0x82, 0x8d, 0x75, 0x5f,
	0x73, 0xce, 0x3d, 0xf7, 0x48, 0x86, 0xd3, 0x98, 0x3e, 0xa4, 0xb1, 0x9b, 0xce, 0x67, 0xee, 0x44,
	0x2e, 0x26, 0x01, 0x97, 0xcc, 0x5f, 0x9d, 0x17, 0xf1, 0x20, 0x65, 0x54, 0x50, 0xd4, 0x28, 0xf5,
	0xec, 0xee, 0x8c, 0xd2, 0xd9, 0x02, 0xbb, 0xaa, 0x35, 0x91, 0x53, 0x17, 0x2f, 0x53, 0xb1, 0xd6,
	0x93, 0xf6, 0x3d, 0xd3, 0x0c, 0x52, 0xe2, 0x06, 0x49, 0x42, 0x45, 0x20, 0x08, 0x4d, 0xb8, 0xe9,
	0x42, 0x48, 0x19, 0xd6, 0xb1, 0xf3, 0xdd, 0x82, 0xe6, 0xa5, 0x14, 0xf1, 0x98, 0xce, 0x71, 0x72,
	0x25, 0x28, 0x6a, 0xc3, 0x9e, 0xc8, 0xe2, 0x8e, 0xd5, 0xb3, 0xfa, 0x75, 0x4f, 0x27, 0xe8, 0x01,
	0xdc, 0xc2, 0x1f, 0x53, 0xc2, 0xd6, 0x7e, 0x24, 0x99, 0x02, 0xeb, 0x54, 0x7a, 0x56, 0x7f, 0xd7,
	0x6b, 0xe9, 0xf2, 0x95, 0xa9, 0xa2, 0xa7, 0x70, 0x68, 0x06, 0x05, 0x59, 0x62, 0x5f, 0x26, 0x44,
	0x74, 0x76, 0x7a, 0x56, 0xbf, 0x35, 0x6c, 0x0d, 0x14, 0xed, 0x98, 0x2c, 0xf1, 0x9b, 0x84, 0x88,
	0xfc, 0x65, 0x9e, 0xa3, 0x53, 0xa8, 0x72, 0x11, 0x08, 0xc9, 0x3b, 0xbb, 0x6a, 0xbe, 0xa9, 0xe7,
	0xaf, 0x55, 0xcd, 0x33, 0x3d, 0xd4, 0x85, 0x3a, 0x4e, 0x04, 0x11, 0x6b, 0x9f, 0x44, 0x9d, 0x3d,
	0xb5, 0x62, 0x4d, 0x17, 0x46, 0x91, 0x13, 0xc2, 0x51, 0xa1, 0xe5, 0x52, 0x08, 0x46, 0x26, 0x52,
	0xe0, 0x4c, 0x94, 0x03, 0x07, 0x81, 0x14, 0xb1, 0xaf, 0xc4, 0x64, 0x2f, 0xb5, 0xb8, 0x46, 0x90,
	0x4f, 0x8f, 0x22, 0x74, 0x08, 0x3b, 0x73, 0xbc, 0x56, 0xb2, 0xea, 0x5e, 0x16, 0x66, 0xa7, 0x58,
	0x05, 0x0b, 0x89, 0x95, 0x80, 0xba, 0xa7, 0x13, 0xe7, 0x25, 0x1c, 0xbc, 0xa2, 0x33, 0x92, 0x78,
	0x98, 0xa7, 0x34, 0xe1, 0x18, 0x3d, 0x81, 0x1a, 0x33, 0xb1, 0xc2, 0x6d, 0x0c, 0x8f, 0x07, 0x25,
	0xa7, 0x06, 0xe5, 0xf3, 0x7a, 0xc5, 0xa8, 0xf3, 0x02, 0x9a, 0x06, 0xe7, 0xbd, 0xc4, 0x5c, 0xa0,
	0xbb, 0xb0, 0x2f, 0x39, 0x66, 0x37, 0xdb, 0x55, 0xb3, 0x74, 0x14, 0x21, 0x1b, 0x6a, 0x69, 0xc0,
	0xf9, 0x07, 0xca, 0x22, 0xb3, 0x5d, 0x91, 0x3b, 0x6f, 0xd5, 0x32, 0x54, 0x8a, 0x7f, 0xa2, 0x1c,
	0x43, 0xad, 0x50, 0xaf, 0x51, 0xf6, 0x85, 0x51, 0x5e, 0x58, 0xbe, 0x53, 0xb2, 0xdc, 0x79, 0x04,
	0xad, 0x1c, 0xda, 0x08, 0xbd, 0x0f, 0xc0, 0x65, 0x18, 0x62, 0xce, 0xa7, 0x72, 0xa1, 0xe0, 0x6b,
	0x5e, 0xa9, 0xe2, 0xf8, 0x70, 0xdb, 0xc3, 0x53, 0x86, 0xb9, 0x96, 0x9b, 0xaf, 0x54, 0x66, 0xb6,
	0x36, 0x99, 0x4b, 0xdb, 0x56, 0x36, 0xb6, 0xdd, 0xbe, 0xd2, 0x6b, 0x68, 0x6f, 0x12, 0xfc, 0x97,
	0x03, 0xc3, 0x6f, 0x15, 0x68, 0x64, 0xad, 0x6b, 0xcc, 0x56, 0x24, 0xc4, 0x68, 0x0c, 0x7b, 0xca,
	0x11, 0xb4, 0xf9, 0xba, 0xec, 0x92, 0x6d, 0x6f, 0x6b, 0x19, 0x47, 0xdb, 0x5f, 0x7e, 0xfc, 0xfc,
	0x5a, 0x69, 0x39, 0x75, 0x77, 0x75, 0xee, 0x2e, 0xb2, 0xd6, 0x85, 0x75, 0x86, 0x42, 0xa8, 0xea,
	0x3b, 0xa2, 0x3f, 0xde, 0xde, 0xf8, 0x66, 0x77, 0xb7, 0xf6, 0x0c, 0x70, 0x4f, 0x01, 0xdb, 0xce,
	0x51, 0x06, 0xfc, 0x29, 0x3f, 0xe6, 0xe7, 0x8c, 0x83, 0x4a, 0x91, 0x91, 0xac, 0xa0, 0x59, 0xbe,
	0x0c, 0xea, 0x6d, 0xc0, 0x6d, 0x71, 0xc5, 0x3e, 0xf9, 0xcb, 0x84, 0xa1, 0x3d, 0x51, 0xb4, 0x5d,
	0xe7, 0xce, 0x6f, 0xb4, 0x4c, 0x0f, 0x5f, 0x58, 0x67, 0xcf, 0x0f, 0xde, 0x35, 0x62, 0xea, 0xd3,
	0xf8, 0x99, 0xfa, 0x4e, 0xaa, 0xea, 0xa7, 0xf2, 0xf8, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef,
	0x07, 0xf5, 0x10, 0xd0, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/bulbasur_v1.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/bulbasur_v1.AuthService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/bulbasur_v1.AuthService/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bulbasur_v1.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bulbasur_v1.AuthService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bulbasur_v1.AuthService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bulbasur_v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ho-oh/pkg/bulbasur_v1/bulbasur.proto",
}
