name: Build and push protocol buffer definitions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: install golang
        run: sudo snap install go --classic
      - name: Compile the protocol buffer files to golang
        env:
          ORIGIN_PATH: ${{ secrets.ORIGIN_PATH }}
        run: make ORIGIN_PATH=${ORIGIN_PATH} build_and_push_go
